CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE EMPLOYEE (
  ID BIGINT DEFAULT NEXT VALUE FOR EMPLOYEE_SEQ,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DEPARTMENT (
    ID BIGINT DEFAULT NEXT VALUE FOR DEPARTMENT_SEQ,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    READ_ONLY BOOLEAN DEFAULT FALSE,
    MANDATORY BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID)
);

CREATE TABLE MAP_EMPLOYEE_DEPARTMENT (
   ID_EMPLOYEE BIGINT NOT NULL,
   ID_DEPARTMENT BIGINT NOT NULL,
   PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT),
   CONSTRAINT FK_EMPLOYEE
       FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID),
   CONSTRAINT FK_DEPARTMENT
       FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT (ID)
);


